// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsepqakwkzmcoazsrvfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZXBxYWt3a3ptY29henNydmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDU2NDMsImV4cCI6MjA1ODYyMTY0M30.SPD1q575Z-aEjahZwaA_dp88BPpdE3K4A594NNpopCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);